version: '3'
services:
    mysql_database:
        image: mariadb:latest
        restart: always
        volumes:
          - ./docker/database.sql:/docker-entrypoint-initdb.d/database.sql
        environment:
            MYSQL_ROOT_PASSWORD: testRootPassword
        command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0 --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306